### ISSUE TITLE
Issue with iOS-Implementation

### ISSUE THREAD

**Issue by piepmax** [julienGrd/BigIslandBarcoding#1] opened 2022-05-02 07:31 UTC
This is the successor to my problem originally reported in https://github.com/Redth/BigIslandBarcoding/issues/14:
I found out that the followig call returns null:
var devices = AVCaptureDevice.DevicesWithMediaType(AVMediaTypes.Video.ToString());

Maybe it's a problem in the current version of Maui. I opened a bug here:
https://github.com/dotnet/maui/issues/6728

**Comment by julienGrd** [comment] 2022-05-02 07:35
@maxulm is this problem happen directly with the BigIslandBarcode project or its with the nuget package ?

**Comment by piepmax** [comment] 2022-05-02 07:49
@julienGrd directly with BigIslandBarcode project

**Comment by julienGrd** [comment] 2022-05-02 07:56
@maxulm OK. In this case we have to wait somebody with Mac/IOS investigate this to go further.

**Comment by stevedayuk** [comment] 2022-05-02 22:43
It seems the AVCaptureDevice.DevicesWithMediaType API has been deprecated by Apple in an earlier version of iOS which is probably why it's now returning a null value. I'm not an expert when it comes to Xamarin/.NET for iOS but I've submitted a pull request which seems to fix this and some other issues I found, and the sample app now works on my physical iPhone 13 Pro running iOS 15.4.1.

**Comment by julienGrd** [comment] 2022-05-03 04:52
@stevedayuk thank you ! I just integrated your PR and publish the 1.0.5 package with it.

@maxulm can you check it solve your problem ?

**Comment by piepmax** [comment] 2022-05-03 05:59
@stevedayuk @julienGrd wow, this is great!
It's the first time the camera working for me! But the recognition of barcodes doesn't work.
The event is not triggered and I get the following stacktrace:

```
Memory around native instruction pointer (0x10035d244):
5e 
f8 1f 
01 00 39 01 00 00 14 a8 03 5f f8  ..^....9......_.
0x10035d244  08 01 40 39 a8 10 00 34 01 00 00 14 
a8 03 5f f8  .
.
@9...4......_.
0x10035d254  08 01 c0 39 08 8d 00 71 e8 13 00 f9 08 69 01 f1  ...9...q.....i..
0x10035d264  c8 0c 00 54 eb 13 40 f9 0a 00 00 90 4a 11 13 91  ...T..@.....J...

```

By the way of coure with the BigIslandSample

@stevedayuk does this work for you?

**Comment by stevedayuk** [comment] 2022-05-03 18:49
> @stevedayuk @julienGrd wow, this is great! It's the first time the camera working for me! But the recognition of barcodes doesn't work. The event is not triggered and I get the following stacktrace:
> 
> ```
> Memory around native instruction pointer (0x10035d244):
> 5e 
> f8 1f 
> 01 00 39 01 00 00 14 a8 03 5f f8  ..^....9......_.
> 0x10035d244  08 01 40 39 a8 10 00 34 01 00 00 14 
> a8 03 5f f8  .
> .
> @9...4......_.
> 0x10035d254  08 01 c0 39 08 8d 00 71 e8 13 00 f9 08 69 01 f1  ...9...q.....i..
> 0x10035d264  c8 0c 00 54 eb 13 40 f9 0a 00 00 90 4a 11 13 91  ...T..@.....J...
> ```
> 
> By the way of coure with the BigIslandSample
> 
> @stevedayuk does this work for you?

Yeah, it's working for me just fine. I'm not getting any values in the debugger in Visual Studio 2022 for Mac RC (though I also didn't get any values while working on the camera fixes either) but I've linked a video where you can see it working and the QR Code URL is being output to the console.

https://drive.google.com/file/d/1RL8n9TpqTalSIqxHLYYJH1QYwV7zSH3_/view

As mentioned previously I'm not an expert on iOS (this is my first time dabbling with .NET for iOS!) so I'm not sure how much help I can be with resolving your issue but what setup are you using to try all this out @maxulm? Are you running the latest versions of macOS on your build machine and, the latest version of iOS on the device you're testing on? Are your Visual Studio 2022 Preview installs up to date?

**Comment by piepmax** [comment] 2022-05-05 07:54
I'm using the latest preview of VS 2022 and iOS 15.4.1 as the latest official release.
But there's one big difference: I'm developing with windows using the MAUI capability of hot restarting.
Maybe it's a problem with the MAUI-Template for iOS-Applications. Is there anyone could test this?

**Comment by piepmax** [comment] 2022-05-06 05:56
I've identified this as the problematic line of code:
`videoDataOutput.SetSampleBufferDelegate(captureDelegate, dispatchQueue);`
(CameraManager.apple.cs line 81)

**Comment by Ihone8** [comment] 2022-05-06 06:00
Hi maxulm , you can scan barcode on ios ? @maxulm

**Comment by Ihone8** [comment] 2022-05-06 06:00
Hi maxulm , you can scan barcode on ios ? @maxulm

**Comment by piepmax** [comment] 2022-05-06 06:17
> Hi maxulm , you can scan barcode on ios ? @maxulm

No, I get the preview, but the event is not fired.

**Comment by Ihone8** [comment] 2022-05-06 06:25
okok thanks

**Comment by stevedayuk** [comment] 2022-05-08 19:17
@maxulm Have you added camera permissions to the Info.plist file? I got a similar "Memory around native instruction pointer" error before I added that but once I did it works on Windows for me just fine.

For clarification, just add the following inside the `<dict>` node in your **Info.plist** file under **Platforms\iOS**:

```    
<key>NSCameraUsageDescription</key>  
<string>Barcode Scanning</string>
````

Also for clarification, the 'NSCameraUsageDescription' key must be entered as is but the text inside the `<string>` node can be whatever you want to be shown when the user is asked for permission to use the camera.

**Comment by piepmax** [comment] 2022-05-09 04:19
@stevedayuk thank you for your reply!
Unfortunately the key is already set.
But maybe it's a device specific problem with my iPhoneX.
I'll try it with an iPhone 12 Pro and report the result.

**Comment by julienGrd** [comment] 2022-05-09 04:47
for information it seem the community work on it https://github.com/CommunityToolkit/Maui/issues/259 : but we don't have release date for now.

**Comment by stevedayuk** [comment] 2022-05-09 07:37
> @stevedayuk thank you for your reply! Unfortunately the key is already set. But maybe it's a device specific problem with my iPhoneX. I'll try it with an iPhone 12 Pro and report the result.

I was hoping that would be a simple fix for you. Fingers crossed you have more luck on the other device.

**Comment by piepmax** [comment] 2022-05-09 11:00
> > @stevedayuk thank you for your reply! Unfortunately the key is already set. But maybe it's a device specific problem with my iPhoneX. I'll try it with an iPhone 12 Pro and report the result.
> 
> I was hoping that would be a simple fix for you. Fingers crossed you have more luck on the other device.

Thank you! I'll give a report :)

**Comment by piepmax** [comment] 2022-05-10 05:22
> > @stevedayuk thank you for your reply! Unfortunately the key is already set. But maybe it's a device specific problem with my iPhoneX. I'll try it with an iPhone 12 Pro and report the result.
> 
> I was hoping that would be a simple fix for you. Fingers crossed you have more luck on the other device.

Unfortunately this also didn't solve the problem. Really strange you did not encounter this problem developing an iOS application under windows :/

**Comment by stevedayuk** [comment] 2022-05-10 07:47
@maxulm I assume you're getting exactly the same error on your other device?

Are you able to upload a sample project that I could compare to my sample to try and work out where the problem is? If you're not able to do so, I could always try and create a working sample and upload that so you could check it out yourself.

**Comment by piepmax** [comment] 2022-05-10 08:41
> @maxulm I assume you're getting exactly the same error on your other device?
> 
> Are you able to upload a sample project that I could compare to my sample to try and work out where the problem is? If you're not able to do so, I could always try and create a working sample and upload that so you could check it out yourself.
I've stored a sample project here:
-
But you can also send me a working sample project, so I can try it out.
Thank you for your support!

**Comment by Ihone8** [comment] 2022-05-24 08:09
@maxulm  Hi. you can run barcode scan on IOS ? 
when I run on the  IOS emulator and got the following error

Microsoft.Maui.Platform.ToPlatformException: 'ZXing.Net.Maui.CameraBarcodeReaderViewHandler found for ZXing.Net.Maui.Controls.CameraBarcodeReaderView is incompatible'

![image](https://user-images.githubusercontent.com/34541083/169982202-18cdb65a-7375-4208-88b3-ea035cda167c.png)

**Comment by piepmax** [comment] 2022-05-24 08:28
> @maxulm Hi. you can run barcode scan on IOS ? when I run on the IOS emulator and got the following error
> 
> Microsoft.Maui.Platform.ToPlatformException: 'ZXing.Net.Maui.CameraBarcodeReaderViewHandler found for ZXing.Net.Maui.Controls.CameraBarcodeReaderView is incompatible'
> 
> ![image](https://user-images.githubusercontent.com/34541083/169982202-18cdb65a-7375-4208-88b3-ea035cda167c.png)

No, I've implemented a photo camera on my own.
But did you see the following post?
https://github.com/julienGrd/BigIslandBarcoding/issues/5

**Comment by Ihone8** [comment] 2022-05-24 08:38
@maxulm 
thanks . I just looked , and it seems to be a different problem.

**Comment by Ihone8** [comment] 2022-05-24 08:49
@maxulm  I can scan on my Iphone

![eaaa68734b1d29df510623310890c41](https://user-images.githubusercontent.com/34541083/169990794-e5d5ffcc-13f6-49ae-8852-7011f29b733c.jpg)

**Comment by piepmax** [comment] 2022-05-24 08:51
Really cool!
Didn't you experience this problem?
https://github.com/julienGrd/BigIslandBarcoding/issues/1#issuecomment-1119283211

**Comment by Ihone8** [comment] 2022-05-24 08:56
No.

**Comment by piepmax** [comment] 2022-05-24 09:17
> No.

Really cool! Could you share your solution?
Maybe in a stripped way, not containing secret code. 
You've compiled on Windows?

**Comment by Ihone8** [comment] 2022-05-24 09:29
@maxulm 
In fact, I don't have any new code. I used nuget package to introduce it

nugetPackage  https://www.nuget.org/packages/ZXing.Net.Maui.Jgdev/    version 1.0.5 is working on ios

Create New Project MAUI
Install ZXing.Net.Maui.Jgdev package
Add.useBarcodereader () to mauiprogram.cs
Create a new Barcode.xaml View The xaml code, add https://github.com/julienGrd/BigIslandBarcoding/blob/main/BigIslandBarcode/MainPage.xaml cs code  same as

Finally, it needs to be released on the iPhone for testing.

**Comment by Ihone8** [comment] 2022-05-24 09:30
@maxulm 
In fact, I don't have any new code. I used nuget package to introduce it

nugetPackage  https://www.nuget.org/packages/ZXing.Net.Maui.Jgdev/    version 1.0.5 is working on ios

Create New Project MAUI
Install ZXing.Net.Maui.Jgdev package
Add.useBarcodereader () to mauiprogram.cs
Create a new Barcode.xaml View The xaml code, add https://github.com/julienGrd/BigIslandBarcoding/blob/main/BigIslandBarcode/MainPage.xaml cs code  same as

Finally, it needs to be released on the iPhone for testing.

**Comment by piepmax** [comment] 2022-05-24 11:10
@Ihone8 
Weird. Which iPhone and iOS-Version did you use?

**Comment by Ihone8** [comment] 2022-05-25 01:04
iPhone : Iphone SE 2 ,  iOS-Version : IOS 15.4.1

**Comment by mobiletonster** [comment] 2022-06-14 03:35
> > @maxulm Hi. you can run barcode scan on IOS ? when I run on the IOS emulator and got the following error
> > Microsoft.Maui.Platform.ToPlatformException: 'ZXing.Net.Maui.CameraBarcodeReaderViewHandler found for ZXing.Net.Maui.Controls.CameraBarcodeReaderView is incompatible'
> > ![image](https://user-images.githubusercontent.com/34541083/169982202-18cdb65a-7375-4208-88b3-ea035cda167c.png)
> 
> No, I've implemented a photo camera on my own. But did you see the following post? #5

I have tried to follow everything in this thread, but I too get this same error.

**Comment by piepmax** [comment] 2022-06-14 04:21
> > > @maxulm Hi. you can run barcode scan on IOS ? when I run on the IOS emulator and got the following error
> > > Microsoft.Maui.Platform.ToPlatformException: 'ZXing.Net.Maui.CameraBarcodeReaderViewHandler found for ZXing.Net.Maui.Controls.CameraBarcodeReaderView is incompatible'
> > > ![image](https://user-images.githubusercontent.com/34541083/169982202-18cdb65a-7375-4208-88b3-ea035cda167c.png)
> > 
> > 
> > No, I've implemented a photo camera on my own. But did you see the following post? #5
> 
> I have tried to follow everything in this thread, but I too get this same error.

I'm pretty sure you didn't.
See https://github.com/julienGrd/BigIslandBarcoding/issues/5
Regards

**Comment by julienGrd** [comment] 2022-10-11 15:18
this project (and associated package) have no reason to live anymore, since the original project ZXing.Net.Maui (https://github.com/Redth/ZXing.Net.Maui) was corrected and a package published. 

Please open issue in the original repository if something still not work

**Closed as completed by julienGrd** 2022-10-11 15:18 UTC
